# Generated by Django 3.2.23 on 2024-03-23 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20240323_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='price',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
