# Generated by Django 3.2.23 on 2024-03-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='member_role',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
