# Generated by Django 3.2.20 on 2023-12-23 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AyojanEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('query', models.TextField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('transaction_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('payment_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('payment_status', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('payment', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BrajYatra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temple_name', models.CharField(blank=True, max_length=500, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='braj_yatra')),
            ],
        ),
        migrations.CreateModel(
            name='DharmikAyojan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='dharmik_ayojan')),
                ('video_link', models.TextField(blank=True, null=True)),
                ('money', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DharmSandesh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='dharm_sandesh_image')),
                ('video_link', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HelpLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=1000, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile', models.CharField(blank=True, max_length=12, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JyotishSamadhan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('dob_place', models.TextField(blank=True, null=True)),
                ('dob_time', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=12, null=True)),
                ('question', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RajatShila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='rajat_shila')),
            ],
        ),
        migrations.CreateModel(
            name='Rashi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='rashi_image')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('img', models.ImageField(null=True, upload_to='services_img/')),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SixBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='six_box_image')),
            ],
        ),
        migrations.CreateModel(
            name='TvLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VastuUpay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='vastu_upay')),
            ],
        ),
        migrations.CreateModel(
            name='BrajYatraDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temple_name', models.CharField(blank=True, max_length=500, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='braj_yatra')),
                ('other_img1', models.FileField(blank=True, default=None, null=True, upload_to='braj_yatra')),
                ('other_img2', models.FileField(blank=True, default=None, null=True, upload_to='braj_yatra')),
                ('other_img3', models.FileField(blank=True, default=None, null=True, upload_to='braj_yatra')),
                ('place', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.place')),
            ],
        ),
    ]
