# Generated by Django 3.2.20 on 2023-12-30 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdsType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, null=True)),
                ('title', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'ads_type',
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advertisement_images')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advertisement.adstype')),
            ],
            options={
                'db_table': 'advertisement',
            },
        ),
    ]
