# Generated by Django 3.2.20 on 2023-12-23 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=1000)),
                ('desc', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('img', models.ImageField(null=True, upload_to='lookup_img/')),
            ],
        ),
        migrations.CreateModel(
            name='ImageFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_folder/')),
            ],
            options={
                'db_table': 'image_folder',
            },
        ),
        migrations.CreateModel(
            name='LookupField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=1000)),
                ('desc', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('img', models.ImageField(null=True, upload_to='lookup_img/')),
                ('pdf', models.FileField(default=None, null=True, upload_to='pdf')),
            ],
        ),
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('desc', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SangthanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sangthan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to='sangthan_image')),
                ('address', models.TextField()),
                ('contact', models.CharField(max_length=20, null=True)),
                ('post', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.sangthantype'),
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, upload_to='lookup_img/')),
                ('image_folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.imagefolder')),
            ],
        ),
    ]
