# Generated by Django 4.2.11 on 2025-09-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_lookupfield_img_alter_lookupfield_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='sangthan',
            name='position',
            field=models.IntegerField(null=True),
        ),
    ]
