# Generated by Django 4.2.11 on 2025-09-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_sangthan_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sangthan',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
