# Generated by Django 4.0 on 2023-07-08 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_post_sangthantype_sangthan_post_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sangthan',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
