# Generated by Django 4.0 on 2023-07-08 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_remove_sangthan_post_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_name', models.CharField(max_length=100, null=True)),
                ('type', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.sangthantype')),
            ],
        ),
        migrations.AddField(
            model_name='sangthan',
            name='post',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='homepage.post'),
        ),
    ]
