# Generated by Django 4.0 on 2023-07-08 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_post_sangthan_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sangthan',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Sangthan',
        ),
        migrations.DeleteModel(
            name='SangthanType',
        ),
    ]
