# Generated by Django 3.2.20 on 2023-12-30 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sangthan_suchi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatraPradeshPadadhikari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('pad', models.CharField(max_length=256, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.ImageField(upload_to='pradesh_padadhikari_image')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('pradesh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sangthan_suchi.pradesh')),
            ],
            options={
                'db_table': 'matra_pradesh_padadhikari',
            },
        ),
        migrations.CreateModel(
            name='MatraNagarPadadhikari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('pad', models.CharField(max_length=256, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.ImageField(upload_to='nagar_padadhikari_image')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('nagar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sangthan_suchi.nagar')),
            ],
            options={
                'db_table': 'matra_nagar_padadhikari',
            },
        ),
        migrations.CreateModel(
            name='MatraDistrictPadadhikari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, null=True)),
                ('pad', models.CharField(max_length=256, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=15, null=True)),
                ('image', models.ImageField(upload_to='district_padadhikari_image')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sangthan_suchi.district')),
            ],
            options={
                'db_table': 'matra_district_padadhikari',
            },
        ),
    ]
